#############################################################################
# Makefile for building: button_control_led
# Generated by qmake (2.01a) (Qt 4.8.7) on: ??. ?.?. 31 12:12:02 2016
# Project:  button_control_led.pro
# Template: app
# Command: /opt/qt-arm/bin/qmake -spec /opt/qt-arm/mkspecs/qws/linux-am335x-g++ -o Makefile button_control_led.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/local/linaro/bin/arm-linux-gnueabihf-gcc
CXX           = /usr/local/linaro/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O3 -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-arm/mkspecs/qws/linux-am335x-g++ -I. -I/opt/qt-arm/include/QtCore -I/opt/qt-arm/include/QtNetwork -I/opt/qt-arm/include/QtGui -I/opt/qt-arm/include -I. -I. -I/media/boon/SANDISKUF/qt-bbb/downloads/tslib/src
LINK          = /usr/local/linaro/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-arm/lib
LIBS          = $(SUBLIBS)  -L/home/boon/qt-bbb/tslib/lib -L/opt/qt-arm/lib -L/home/boon/qt-bbb/tslib/lib -lts -lQtGui -L/opt/qt-arm/lib -lQtNetwork -lQtCore -lpthread 
AR            = /usr/local/linaro/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = /usr/local/linaro/bin/arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		GPIO/GPIOConst.cpp \
		GPIO/GPIOManager.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		GPIOConst.o \
		GPIOManager.o \
		moc_mainwindow.o
DIST          = /opt/qt-arm/mkspecs/common/unix.conf \
		/opt/qt-arm/mkspecs/common/linux.conf \
		/opt/qt-arm/mkspecs/common/gcc-base.conf \
		/opt/qt-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-arm/mkspecs/common/g++-base.conf \
		/opt/qt-arm/mkspecs/common/g++-unix.conf \
		/opt/qt-arm/mkspecs/common/qws.conf \
		/opt/qt-arm/mkspecs/qconfig.pri \
		/opt/qt-arm/mkspecs/features/qt_functions.prf \
		/opt/qt-arm/mkspecs/features/qt_config.prf \
		/opt/qt-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt-arm/mkspecs/features/default_pre.prf \
		/opt/qt-arm/mkspecs/features/release.prf \
		/opt/qt-arm/mkspecs/features/default_post.prf \
		/opt/qt-arm/mkspecs/features/shared.prf \
		/opt/qt-arm/mkspecs/features/warn_on.prf \
		/opt/qt-arm/mkspecs/features/qt.prf \
		/opt/qt-arm/mkspecs/features/unix/thread.prf \
		/opt/qt-arm/mkspecs/features/moc.prf \
		/opt/qt-arm/mkspecs/features/resources.prf \
		/opt/qt-arm/mkspecs/features/uic.prf \
		/opt/qt-arm/mkspecs/features/yacc.prf \
		/opt/qt-arm/mkspecs/features/lex.prf \
		/opt/qt-arm/mkspecs/features/include_source_dir.prf \
		button_control_led.pro
QMAKE_TARGET  = button_control_led
DESTDIR       = 
TARGET        = button_control_led

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: button_control_led.pro  /opt/qt-arm/mkspecs/qws/linux-am335x-g++/qmake.conf /opt/qt-arm/mkspecs/common/unix.conf \
		/opt/qt-arm/mkspecs/common/linux.conf \
		/opt/qt-arm/mkspecs/common/gcc-base.conf \
		/opt/qt-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-arm/mkspecs/common/g++-base.conf \
		/opt/qt-arm/mkspecs/common/g++-unix.conf \
		/opt/qt-arm/mkspecs/common/qws.conf \
		/opt/qt-arm/mkspecs/qconfig.pri \
		/opt/qt-arm/mkspecs/features/qt_functions.prf \
		/opt/qt-arm/mkspecs/features/qt_config.prf \
		/opt/qt-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt-arm/mkspecs/features/default_pre.prf \
		/opt/qt-arm/mkspecs/features/release.prf \
		/opt/qt-arm/mkspecs/features/default_post.prf \
		/opt/qt-arm/mkspecs/features/shared.prf \
		/opt/qt-arm/mkspecs/features/warn_on.prf \
		/opt/qt-arm/mkspecs/features/qt.prf \
		/opt/qt-arm/mkspecs/features/unix/thread.prf \
		/opt/qt-arm/mkspecs/features/moc.prf \
		/opt/qt-arm/mkspecs/features/resources.prf \
		/opt/qt-arm/mkspecs/features/uic.prf \
		/opt/qt-arm/mkspecs/features/yacc.prf \
		/opt/qt-arm/mkspecs/features/lex.prf \
		/opt/qt-arm/mkspecs/features/include_source_dir.prf \
		/opt/qt-arm/lib/libQtGui.prl \
		/opt/qt-arm/lib/libQtNetwork.prl \
		/opt/qt-arm/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qt-arm/mkspecs/qws/linux-am335x-g++ -o Makefile button_control_led.pro
/opt/qt-arm/mkspecs/common/unix.conf:
/opt/qt-arm/mkspecs/common/linux.conf:
/opt/qt-arm/mkspecs/common/gcc-base.conf:
/opt/qt-arm/mkspecs/common/gcc-base-unix.conf:
/opt/qt-arm/mkspecs/common/g++-base.conf:
/opt/qt-arm/mkspecs/common/g++-unix.conf:
/opt/qt-arm/mkspecs/common/qws.conf:
/opt/qt-arm/mkspecs/qconfig.pri:
/opt/qt-arm/mkspecs/features/qt_functions.prf:
/opt/qt-arm/mkspecs/features/qt_config.prf:
/opt/qt-arm/mkspecs/features/exclusive_builds.prf:
/opt/qt-arm/mkspecs/features/default_pre.prf:
/opt/qt-arm/mkspecs/features/release.prf:
/opt/qt-arm/mkspecs/features/default_post.prf:
/opt/qt-arm/mkspecs/features/shared.prf:
/opt/qt-arm/mkspecs/features/warn_on.prf:
/opt/qt-arm/mkspecs/features/qt.prf:
/opt/qt-arm/mkspecs/features/unix/thread.prf:
/opt/qt-arm/mkspecs/features/moc.prf:
/opt/qt-arm/mkspecs/features/resources.prf:
/opt/qt-arm/mkspecs/features/uic.prf:
/opt/qt-arm/mkspecs/features/yacc.prf:
/opt/qt-arm/mkspecs/features/lex.prf:
/opt/qt-arm/mkspecs/features/include_source_dir.prf:
/opt/qt-arm/lib/libQtGui.prl:
/opt/qt-arm/lib/libQtNetwork.prl:
/opt/qt-arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qt-arm/mkspecs/qws/linux-am335x-g++ -o Makefile button_control_led.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/button_control_led1.0.0 || $(MKDIR) .tmp/button_control_led1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/button_control_led1.0.0/ && $(COPY_FILE) --parents mainwindow.h GPIO/GPIOConst.h GPIO/GPIOManager.h .tmp/button_control_led1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp GPIO/GPIOConst.cpp GPIO/GPIOManager.cpp .tmp/button_control_led1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/button_control_led1.0.0/ && (cd `dirname .tmp/button_control_led1.0.0` && $(TAR) button_control_led1.0.0.tar button_control_led1.0.0 && $(COMPRESS) button_control_led1.0.0.tar) && $(MOVE) `dirname .tmp/button_control_led1.0.0`/button_control_led1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/button_control_led1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: GPIO/GPIOManager.h \
		GPIO/GPIOConst.h \
		mainwindow.h
	/opt/qt-arm/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/qt-arm/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		GPIO/GPIOManager.h \
		GPIO/GPIOConst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		GPIO/GPIOManager.h \
		GPIO/GPIOConst.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

GPIOConst.o: GPIO/GPIOConst.cpp GPIO/GPIOConst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GPIOConst.o GPIO/GPIOConst.cpp

GPIOManager.o: GPIO/GPIOManager.cpp GPIO/GPIOManager.h \
		GPIO/GPIOConst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GPIOManager.o GPIO/GPIOManager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/root/ || $(MKDIR) $(INSTALL_ROOT)/root/ 
	-$(INSTALL_PROGRAM) /home/boon/qtprojects/button_control_led/button_control_led $(INSTALL_ROOT)/root/


uninstall_target:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/root/button_control_led
	-$(DEL_DIR) $(INSTALL_ROOT)/root/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

